// React/src/App.js
import React, { useState, useRef, useCallback } from "react";
import "devextreme/dist/css/dx.light.css";

import { DropDownBox } from "devextreme-react/drop-down-box";
import { List } from "devextreme-react/list";
 
const fruits = ["Apples", "Oranges", "Lemons", "Pears", "Pineapples"];

function App() {
    const [selectedFruit, setSelectedFruit] = useState('');
    const [dataSource, setDataSource] = useState(fruits);
    const dropDownBoxRef = useRef(null);
    const listRef = useRef(null);
    const changeDropDownBoxValue = useCallback((arg) => {
        setSelectedFruit(arg.addedItems[0]);
        dropDownBoxRef.current.instance.close();
    }, []);
    const onValueChanged = useCallback((e) => {
        setSelectedFruit(e.value);
    }, []);
    const addItem = useCallback(() => {
        setDataSource([...dataSource, selectedFruit]);
        setSelectedFruit('');
        listRef.current.instance.reload();
    }, [dataSource, selectedFruit]);
    const onItemDeleting = useCallback((e) => {
        if (dataSource.length === 1) {
            e.cancel = true;
        }
    }, [dataSource]);

    return (
        <div id="container">
            <DropDownBox
                value={selectedFruit}
                dataSource={dataSource}
                ref={dropDownBoxRef}
                label="Fruits"
                labelMode="floating"
                onValueChanged={onValueChanged}
                acceptCustomValue={true}
                openOnFieldClick={false}
                onEnterKey={addItem}
            >
                <List
                    ref={listRef}
                    dataSource={dataSource}
                    selectionMode="single"
                    onSelectionChanged={changeDropDownBoxValue}
                    allowItemDeleting={true}
                    onItemDeleting={onItemDeleting}
                />
            </DropDownBox>
        </div>
    );
}

export default App;

// Vue/src/App.vue
<template>
    <div id="container">
        <DxDropDownBox
            :accept-custom-value="true"
            :open-on-field-click="false"
            v-model:value="selectedFruit"
            v-model:opened="isDropDownBoxOpened"
            :data-source="dataSource"
            label="Fruits"
            labelMode="floating"
            @enter-key="addItem"
        >
            <DxList
                :data-source="dataSource"
                selection-mode="single"
                @selection-changed="changeDropDownBoxValue($event)"
                :allow-item-deleting="true"
                @item-deleting="onItemDeleting($event)"
                @initialized="saveListInstance"
            >
            </DxList>
        </DxDropDownBox>
    </div>
</template>

<script>
import 'devextreme/dist/css/dx.light.css';
import DxDropDownBox from "devextreme-vue/drop-down-box";
import DxList from "devextreme-vue/list";

export default {
    components: {
        DxDropDownBox,
        DxList
    },
    data() {
        const fruits = ["Apples", "Oranges", "Lemons", "Pears", "Pineapples"];
        return {
            dataSource: fruits,
            isDropDownBoxOpened: false,
            selectedFruit: '',
            listInstance: null
        }
    },
    methods: {
        changeDropDownBoxValue(e) {
            this.selectedFruit = e.addedItems[0];
            this.isDropDownBoxOpened = false;
        },
        onItemDeleting(e) {
            if (this.dataSource.length === 1) {
                e.cancel = true;
            }
        },
        saveListInstance(e) {
            this.listInstance = e.component;
        },
        addItem() {
            this.dataSource.push(this.selectedFruit);
            this.selectedFruit = '';
            this.listInstance.reload();
        }
    }
}
</script>

<style>
    #container {
        width: 350px;
    }
</style>
